// Import the functions you need from the SDKs you need
import { initializeApp } from "https://www.gstatic.com/firebasejs/9.22.1/firebase-app.js";
import { getDatabase, ref, set } from "https://www.gstatic.com/firebasejs/9.22.1/firebase-database.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/9.22.1/firebase-auth.js";

// Your web app's Firebase configuration
const firebaseConfig = {
  apiKey: "AIzaSyDsU_xDm-E8w4_j74zgQqzolsy-esKuEzs",
  authDomain: "fyp0-b60d4.firebaseapp.com",
  databaseURL: "https://fyp0-b60d4-default-rtdb.europe-west1.firebasedatabase.app/",
  projectId: "fyp0-b60d4",
  storageBucket: "fyp0-b60d4.appspot.com",
  messagingSenderId: "47322184279",
  appId: "1:47322184279:web:c4c74120499560f8414112",
  measurementId: "G-ZDHGZCRH2H"
};

console.log("JavaScript file is connected!");

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const db = getDatabase(app);
const auth = getAuth();

const questions = [
    {
      question: "What are the primary pollutants responsible for air pollution?",
      options: ["Aerosols and methane", "Particulate matter and sulfur dioxide", "Nitrogen oxides and ozone"],
      correctAnswer: "Particulate matter and sulfur dioxide",
      explanation: "Particulate matter (PM) and sulfur dioxide (SO2) are among the primary pollutants contributing to air pollution, as mentioned in the content."
    },
    {
      question: "How is carbon monoxide (CO) mainly produced?",
      options: ["By burning fossil fuels containing sulfur", "During combustion at high temperatures", "Through incomplete combustion of fossil fuels"],
      correctAnswer: "Through incomplete combustion of fossil fuels",
      explanation: "Carbon monoxide (CO) is produced by incomplete combustion of fossil fuels in various processes, as stated in the content."
    },
    {
      question: "Which gas contributes to the formation of ground-level ozone (O3)?",
      options: ["Nitrogen oxides (NOx)", "Volatile organic compounds (VOCs)", "Carbon monoxide (CO)"],
      correctAnswer: "Nitrogen oxides (NOx)",
      explanation: "Ground-level ozone forms through chemical reactions involving nitrogen oxides (NOx) and volatile organic compounds (VOCs), as mentioned in the content."
    },
    {
      question: "What is the primary source of methane (CH4) emissions?",
      options: ["Vehicle exhaust", "Agricultural activities", "Industrial processes"],
      correctAnswer: "Agricultural activities",
      explanation: "Methane (CH4) is emitted from sources like agricultural activities, including livestock digestion, as highlighted in the content."
    },
    {
      question: "What role do aerosols play in Earth's climate?",
      options: ["Cooling the planet by absorbing sunlight", "Warming the planet by reflecting sunlight", "Absorbing greenhouse gases"],
      correctAnswer: "Warming the planet by reflecting sunlight",
      explanation: "Aerosols can reflect or absorb sunlight, contributing to warming trends on Earth, as described in the content."
    },
    {
      question: "How does exposure to polluted air affect human health?",
      options: ["Increases immunity", "Causes respiratory diseases", "Enhances cardiovascular function"],
      correctAnswer: "Causes respiratory diseases",
      explanation: "Exposure to polluted air can lead to respiratory diseases, among other health issues, as mentioned in the content."
    },
    {
      question: "What is the significance of continuous air quality monitoring?",
      options: ["It helps in increasing pollution levels", "It ensures cleaner air", "It provides early warnings of health risks"],
      correctAnswer: "It provides early warnings of health risks",
      explanation: "Continuous air quality monitoring is essential for providing early warnings of health risks associated with air pollution, as highlighted in the content."
    },
    {
        question: "Which gas is known as a greenhouse gas and contributes to global warming?",
        options: ["Ozone (O3)", "Carbon monoxide (CO)", "Methane (CH4)"],
        correctAnswer: "Methane (CH4)",
        explanation: "Methane (CH4) is a potent greenhouse gas that contributes to global warming, as mentioned in the content."
      },
      {
        question: "What is the main source of sulfur dioxide (SO2) emissions?",
        options: ["Vehicle exhaust", "Burning fossil fuels containing sulfur", "Industrial waste"],
        correctAnswer: "Burning fossil fuels containing sulfur",
        explanation: "Sulfur dioxide (SO2) is primarily generated by burning fossil fuels containing sulfur, such as coal and oil, as stated in the content."
      },
      {
        question: "How does ozone (O3) at ground level affect human health?",
        options: ["It enhances immune function", "It causes respiratory problems", "It promotes cardiovascular health"],
        correctAnswer: "It causes respiratory problems",
        explanation: "Ground-level ozone (O3) can cause respiratory problems and other health issues in humans, as mentioned in the content."
      }  ];
  
  

      document.addEventListener('DOMContentLoaded', function() {

        function updateQuizCompletion(quizScore) {
            // Get the current user
            const currentUser = auth.currentUser;
            
            if (currentUser) {
                // If user is logged in, get the user ID
                const userId = currentUser.uid;
                
                // Reference to the user's progress in the database
                const userProgressRef = ref(db, `users/${userId}/progress/airPollution/quizCompletion`);
                
                // Update quiz completion data in the database
                set(userProgressRef, {
                    quizScore: quizScore * 10// Save the quiz score
                }, { merge: true }).then(() => {
                    console.log('Quiz completion data updated successfully.');
                }).catch((error) => {
                    console.error('Error updating quiz completion data:', error);
                });
            } else {
                console.error('No user is currently logged in.');
            }
        }
        
      // Put your JavaScript code here
      const userResponses = [];
      let score = 0;
    
      let currentQuestionIndex = 0; // Variable to keep track of the current question index
      function closeModal() {
        const modal = document.getElementById('myModal');
        modal.style.display = 'none';
    }
    
      function displayQuestion() {
          const questionContainer = document.getElementById('questionContainer');
          const questionNum = document.getElementById('questionnum');
          const quizForm = document.getElementById('quizForm');
    
          // Clear previous question and options
          questionContainer.innerHTML = '';
          quizForm.innerHTML = '';
    
          // Check if there are more questions
          if (currentQuestionIndex >= questions.length) {
              // No more questions, show quiz recap
              showRecap();
              // Close the modal
              closeModal();
              return;
          }
    
          // Get the current question
          const currentQuestion = questions[currentQuestionIndex];
    
          // Display question number
          questionNum.textContent = `Question ${currentQuestionIndex + 1}`;
    
          // Display question
          const questionElement = document.createElement('p');
          questionElement.textContent = currentQuestion.question;
          questionContainer.appendChild(questionElement);
    
          // Display options
          currentQuestion.options.forEach((option, index) => {
              const optionDiv = document.createElement('div'); // Create a div for each option
              const optionElement = document.createElement('label');
              optionElement.innerHTML = `
                  <input type="radio" name="answer" value="${option}">
                  ${option}
              `;
              optionDiv.appendChild(optionElement); // Append the option to the div
              quizForm.appendChild(optionDiv); // Append the div to the form
    
          });
    
            // Add submit button
            const submitButton = document.createElement('button');
            submitButton.textContent = 'Submit Answer';
            quizForm.appendChild(submitButton);
    
            // Handle form submission
            submitButton.addEventListener('click', function(event) {
                event.preventDefault(); // Prevent form submission
                const selectedOption = quizForm.querySelector('input[name="answer"]:checked');
                if (!selectedOption) {
                    alert('Please select an answer.');
                    return;
                }
                const answer = selectedOption.value;
                const correctAnswer = questions[currentQuestionIndex].correctAnswer;
                checkAnswer(answer, correctAnswer);
            });
        }
    
          // Function to check answer
          function checkAnswer(answer, correctAnswer) {
            // Push user's response to userResponses array
            userResponses.push(answer);
            if (answer === correctAnswer) {
                // Correct answer
                // You can add your logic for what to do when the answer is correct
                score++; // Increment the score for correct answer
            }
            // Move to the next question
            currentQuestionIndex++;
            displayQuestion();
    
    
     
            updateQuizCompletion(score);
    
    
        }
    
    
        function showRecap() {
          const scorePercentage = (score / questions.length) * 100;
          const recapSection = document.getElementById('recapSection');
          recapSection.style.display = 'block';
          recapSection.innerHTML = `
              <div style="text-align:center;" class="recap-header">
                  <h3>Score: ${scorePercentage}% (${score}/${questions.length})</h3>
              </div>`;
          
          questions.forEach((question, index) => {
              const questionDiv = document.createElement('div');
              questionDiv.classList.add('recap-question');
              questionDiv.innerHTML = `
                  <div class="recap-item">
                      <h4>Question</strong> ${index + 1}: ${question.question}</h4>
                      <p><strong>Your Response:</strong> ${userResponses[index]}</p>
                      <p><strong>The Correct Answer:</strong> ${question.correctAnswer}</p>
                      <p><strong>Explanation:</strong> ${question.explanation}</p>
                  </div>`;
              recapSection.appendChild(questionDiv);
          });
      
          const currentUser = auth.currentUser;
          if (currentUser) {
              const userId = currentUser.uid;
              const userScoreRef = ref(db, `users/${userId}/progress/airPollution/quizCompletion`);
              set(userScoreRef, {
                  quizScore: scorePercentage // Save the quiz score percentage
              }, { merge: true }).then(() => {
                  console.log('Score percentage saved successfully.');
              }).catch((error) => {
                  console.error('Error saving score percentage:', error);
              });
          } else {
              console.error('No user is currently logged in.');
          }
      
          // Hide the modal
          const modal = document.getElementById('myModal');
          modal.style.display = 'none';
      }
      
      
    
      // Call displayQuestion function to start the quiz
      displayQuestion();
    });